# Generated by Django 4.1.1 on 2023-10-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_articulos_cantidad_alter_articulos_descuento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'curso'},
        ),
    ]
