# Generated by Django 4.1.1 on 2023-10-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='operacion',
            field=models.CharField(default='Asingacion', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='operacion',
            field=models.CharField(default='Asignacion', max_length=50),
        ),
    ]
