# Generated by Django 4.1.1 on 2023-10-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_pedido_entregado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'pedido', 'verbose_name_plural': 'Aprobacion'},
        ),
    ]
