# Generated by Django 4.1.1 on 2023-10-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'curso'},
        ),
    ]
