# Generated by Django 4.1.1 on 2023-10-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuarios_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Alumnos'},
        ),
    ]
